addReviewers: true
addAssignees: false

numberOfReviewers: 2

useReviewGroups: true

reviewGroups:
  reviewer:
    - 1ilit
    - CENTneRMOB
  maintainer:
    - dsavitskiiquantori
    - StanAtWork
    - andreypoletaev2
    - PavelYakupov-FOG
