addReviewers: true
addAssignees: false

numberOfReviewers: 1

useReviewGroups: true

reviewGroups:
  reviewer:
    - catherineisonline
    - KaaRinnna
    - AkerkeMilano
    - the-boy-al
    - 1ilit
  maintainer:
    - dsavitskiiquantori
    - StanAtWork
    - andreypoletaev2
    - PavelYakupov-FOG
