addReviewers: true
addAssignees: false

numberOfReviewers: 2

useReviewGroups: true

reviewGroups:
  reviewer:
    - Anna1-991
    - catherineisonline
    - KaaRinnna
    - AkerkeMilano
    - the-boy-al
  maintainer:
    - dsavitskiiquantori
    - StanAtWork
    - andreypoletaev2
    - PavelYakupov-FOG
