version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: fe
    ports:
      - '8080:80'
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: be
    ports:
      - '3000:3000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
