services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend
    ports:
      - '80:80'
      - '443:443'
    networks:
      - app-network
    volumes:
      - ../certs:/etc/nginx/certs:ro
      - .github/workflows/nginx.conf:/etc/nginx/nginx.conf:ro

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
