name: 'auto-mention-action'
description: 'This is a action that mention pull request reviewers'
runs:
  using: 'node20'
  main: 'dist/index.js'

inputs:
  repo-token:
    description: 'A token for the repo'
    default: ${{ github.token }}
    required: false
  configuration-path:
    description: 'A path for the auto-mention configuration'
    default: '.github/auto_assign.yml'
