name: Auto Assign

on:
  pull_request:
    types: [opened]

jobs:
  code-review:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - id: labeler
        uses: actions/labeler@v5

      - uses: actions/checkout@v4

      - name: Auto-assign for FE
        if: contains(steps.labeler.outputs.all-labels, 'frontend')
        uses: ./.github/actions/auto-mention-action
        with:
          configuration-path: '.github/auto-assign-fe.yaml'

      - name: Auto-assign for BE
        if: contains(steps.labeler.outputs.all-labels, 'backend')
        uses: ./.github/actions/auto-mention-action
        with:
          configuration-path: '.github/auto-assign-be.yaml'
