name: Auto Assign

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Auto-assign for FE
        if: contains(github.event.pull_request.labels.*.name, 'frontend')
        uses: kentaro-m/auto-assign-action@v2
        with:
          configuration-path: '.github/auto-assign-fe.yaml'

      - name: Auto-assign for BE
        if: contains(github.event.pull_request.labels.*.name, 'backend')
        uses: kentaro-m/auto-assign-action@v2
        with:
          configuration-path: '.github/auto-assign-be.yaml'
