name: Auto Assign

on:
  pull_request:
    types: [labeled, opened, synchronize, reopened]

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/labeler@v5
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Auto-assign for FE
        if: contains(github.event.pull_request.labels.*.name, 'frontend')
        uses: ./.github/actions/auto-mention-action
        with:
          configuration-path: '.github/auto-assign-fe.yaml'

      - name: Auto-assign for BE
        if: contains(github.event.pull_request.labels.*.name, 'backend')
        uses: ./.github/actions/auto-mention-action
        with:
          configuration-path: '.github/auto-assign-be.yaml'
